os: Visual Studio 2015
version: "{build}"
build: off
platform: x64
environment:
  VIPS_VERSION_MAJOR_MINOR: 8.1
  VIPS_VERSION_PATCH: 1
  VIPS_WARNING: 0
  matrix:
  - nodejs_version: "0.12"
  - nodejs_version: "4"
install:
  - ps: $env:VIPS_VERSION = "$env:VIPS_VERSION_MAJOR_MINOR.$env:VIPS_VERSION_PATCH"
  - ps: Write-Output "Fetching http://www.vips.ecs.soton.ac.uk/development/vips-dev-w64-$env:VIPS_VERSION-1.zip"
  - ps: Start-FileDownload http://www.vips.ecs.soton.ac.uk/development/vips-dev-w64-$env:VIPS_VERSION-1.zip -FileName c:\vips-dev-$env:VIPS_VERSION.zip
  - ps: Invoke-Expression "& 7z -y x c:\vips-dev-$env:VIPS_VERSION.zip -oc:\ | FIND /V `"ing  `""
  - ps: $env:VIPS_HOME = "c:\vips-dev-$env:VIPS_VERSION"
  - ps: $env:PATH = "$env:VIPS_HOME\bin;$env:PATH"
  - ps: Install-Product node $env:nodejs_version x64
  - npm install
test_script:
  - npm run-script test-win
